set nocompatible
set autoindent
set backspace=indent,eol,start
set complete-=i
set smarttab
set number
set ttimeout
set ttimeoutlen=100
set expandtab

"=== Vundle ===

" don't Automatically detect file types.
filetype on
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle' 
" original repos on github
Bundle 'vimoutliner/vimoutliner'
Bundle 'lyokha/vim-xkbswitch'
Bundle 'bkad/CamelCaseMotion'                      
Bundle 'kien/ctrlp.vim'
Bundle 'vim-scripts/ZoomWin'                       
Bundle 'vim-scripts/Color-Sampler-Pack'            
Bundle 'vim-scripts/MailApp'                       
Bundle 'vim-scripts/ScrollColors'                  
Bundle 'vim-scripts/translit_converter'            
Bundle 'tpope/vim-ragtag'                          
Bundle 'slack/vim-bufexplorer'                     
Bundle 'altercation/vim-colors-solarized'          
Bundle 'kchmck/vim-coffee-script'                  
Bundle 'Lokaltog/vim-easymotion'                   
Bundle 'mattn/gist-vim'                            
Bundle 'itspriddle/vim-jquery'                     
Bundle 'michaeljsmith/vim-indent-object'           
Bundle 'vim-scripts/Conque-Shell'
Bundle 'tpope/vim-pastie'                          
Bundle 'gerardc/vim-padrino'                       
Bundle 'tpope/vim-repeat'                          
Bundle 'tpope/vim-speeddating'                     
Bundle 'tpope/vim-markdown'                        
Bundle 'cakebaker/scss-syntax.vim'                 
Bundle 'sophacles/vim-outliner'                    
Bundle 'bbommarito/vim-slim'                       
Bundle 'tpope/vim-rails'                           
Bundle 'tpope/vim-cucumber'                        
Bundle 'tpope/vim-haml'                            
Bundle 'scrooloose/nerdtree'                       
Bundle 'mileszs/ack.vim'                           
Bundle 'godlygeek/tabular'                         
Bundle 'tpope/vim-fugitive'                        
Bundle 'srushti/snipmate.vim'                      
Bundle 'scrooloose/nerdcommenter'                  
Bundle 'duff/vim-bufonly'                          
Bundle 'tpope/vim-endwise'                         
Bundle 'tpope/vim-surround'                        
Bundle 'tpope/vim-unimpaired'                      
Bundle 'tpope/vim-rake'                            
Bundle 'pangloss/vim-javascript'                   
Bundle 'Townk/vim-autoclose'                       
Bundle 'ecomba/vim-ruby-refactoring'               
Bundle 'nelstrom/gundo.vim'                        
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'stacruz/sparkup.git'
Bundle 'jpalardy/vim-slime.git'
Bundle 'duff/vim-scratch'
Bundle 'vim-scripts/Rainbow-Parenthesis'
Bundle 'docunext/closetag.vim'
Bundle 'kevinw/pyflakes-vim'
Bundle 'vim-scripts/Better-CSS-Syntax-for-Vim'
Bundle 'skammer/vim-css-color'
Bundle 'Raimondi/delimitMate'
Bundle 'granin/nvim'
"Bundle 'tpope/vim-pathogen'                        
"Bundle 'danchoi/soywiki'                            
"Bundle 'vim-scripts/YankRing.vim'
"Bundle 'shemerey/vim-project'                      
"Bundle 'vim-scripts/netrw.vim'                     
"Bundle 'tsaleh/vim-align'                          
"Bundle 'vim-scripts/vimwiki.git'                   
"Bundle 'hallettj/jslint.vim'                       
"Bundle 'jcf/rvm_ruby.vim'                          
"Bundle 'Lokaltog/vim-powerline'
"Bundle 'robgleeson/hammer.vim'                     
"Bundle 'khussein/vimchat.git'   
"Bundle 'ervandew/supertab'     "kills autocompletion
"Bundle 'minibufexpl.vim'       "doesn't stict to bottom so takes space
"when window is resized
"Bundle 'godlygeek/csapprox'    "kills colorschemes in terminal, works
"after sourcing vimrc again
"Bundle 'shemerey/vim-peepopen' "no need as i live in terminal
"Bundle 'chrismetcalf/vim-yankring'               "obstricts ctrlp

" vim-scripts repos
" Bundle 'L9'
"Bundle 'FuzzyFinder'

" non github repos
"Bundle 'git://git.wincent.com/command-t.git'
"

"------------------------------------------------------------------------
let g:XkbSwitchEnabled = 1 
let g:XkbSwitchIMappings = ['ru']


"------------------------------------------------------------------------
" === Russian language ===

if has("unix")
    " кодировка по-умолчанию
    set encoding=utf-8
endif
" порядок перебора кодировок
set fileencodings=utf-8,windows-1251,iso-8859-15,koi8-r
" порядок перебора типов EOL
set fileformats=unix,dos,mac

set incsearch
" Use <C-L> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :nohlsearch<CR><C-L>
endif
set laststatus=2
set ruler
set showcmd
set wildmenu
" хранить больше истории команд ...
set history=1000     " keep 50 lines of command line history
" ... и правок
set undolevels=2048
" меньше приоритета бинарным файлам при автодополнении
set suffixes+=.png,.gif,.jpg,.jpeg,.ico

" показывать имя буфера в заголовке терминала
set title
" формат заголовка
set titlestring=%t%(\ %m%)%(\ %r%)%(\ %h%)%(\ %w%)%(\ (%{expand(\"%:p:~:h\")})%)\ -\ VIM
" показывать совпадающие скобки для HTML-тегов
set matchpairs+=<:>

"=== Appearnace ===
set t_Co=256 " 256 colors
syntax on " syntax highlighting
" Default color scheme
colorscheme solarized
set background=dark

" load the plugin and indent settings for the detected filetype 
filetype plugin on
filetype plugin indent on

highlight lCursor guifg=NONE guibg=Cyan

" Omni Completion **********************
if has('autocmd')
  autocmd FileType html :set omnifunc=htmlcomplete#CompleteTags
  autocmd FileType python set omnifunc=pythoncomplete#Complete
  autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
  autocmd FileType css set omnifunc=csscomplete#CompleteCSS
  autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
  autocmd FileType php set omnifunc=phpcomplete#CompletePHP
  autocmd FileType c set omnifunc=ccomplete#Complete
  autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete " may require ruby compiled in
endif

" хранить swap в отдельном каталоге
set directory=~/.vim/swap/
" включить сохранение резервных копий
set backup
"backup system 
" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" === Remaping ===
"WINDOWS
"=========================================
"http://www.derekwyatt.org/vim/the-vimrc-file/walking-around-your-Windows/

noremap <silent> - <C-W>
nmap <silent> <unique> <leader><leader> :wincmd w<cr>

" Close the window below this one
noremap <silent> +J :wincmd j<cr>:close<cr>

" Close the window above this one
noremap <silent> +K :wincmd k<cr>:close<cr>

" Close the window to the left of this one
noremap <silent> +H :wincmd h<cr>:close<cr>

" Close the window to the right of this one
noremap <silent> +L :wincmd l<cr>:close<cr>

"EDIT / SOURCES FILES
map <Leader>v :vsp ~/.vimrc<CR>

imap OA <ESC>kli
imap OB <ESC>jli
imap OC <ESC>lli
imap OD <ESC>hli

nmap <silent> <unique> <leader>q :wa<CR>:qa<CR>

" === Other stuff ===
if has("autocmd")
  autocmd bufwritepost .vimrc source $MYVIMRC
endif

" === аббревиатуры ===
 
" дизайнерская рыба
inoreabbrev lorem Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.<C-O>:call EatChar()<CR>
" autocorrection 
iab gh. GitHub
iab verr version
iab winn windows
iab US United States
iab seva Seva
iab sadhana Sadhana
iab satsang Satsang
" From Typinator 20705
iab zgotit did you get the message below? 
"iab .tt .textile
"iab b&t Books and Tapes
"iab : :)
iab .c. .com
iab .o. .org
iab hse he/she 
iab ill I'll 
iab Ill I'll
iab xgth пересыла
iab xap application 
iab xru Russia 
iab xaol Art of Living
iab xbs brainstorm
iab xdev develop
iab xfb Facebook 
iab xfl flickr 
iab xfw forward
iab xg google
iab xgui graphical user interface
iab xgj Guruji
iab xww http://www.{^}.com
iab xdu https://dl.dropbox.com/u/347817/
iab xikt Irkutsk
iab xmow Moscow
iab xkgd Kaliningrad
iab xspb St. Petersburg
iab xksk Krasnoyarsk
iab xkrr Krasnodar
iab xkbd keyboard
iab xe email
iab x! Misha Granin
iab x@ @granin.net
iab xn @granin.net
iab xM Misha
iab xG Granin
iab xmsg message
iab xm Misha
iab xg Granin
iab xna next action
iab xos open source 
iab xosp open source project 
iab xoss open source software
iab xru russian
iab xRu Russia
iab xsk skype: 
iab xdb DropBox
" Russian
iab ,l.  DropBox
iab ьдб  DropBox
